# Write the code that execute the following:

### Output:  We School

In [1]:
print ("we school")

we school

### Declare variable with initial value 6 and print it

In [3]:
x = 2
y = 3
print (y*x)

6

### Declare variable with initial value your name and print it

In [4]:
x= "Abdelrahman"
y= "Amr"
print (x+y)

AbdelrahmanAmr

### Print the following output (WeSchool 2021) by using two variables

In [8]:
d="we school"
a="2021"
print (d+a)

we school2021

### Declare three variables x,y & z with initial values 1,2 & 3 in one line then print them

In [9]:
(z,y,x)=(1,2,3)
print(z)
print(y)
print(x)

1
2
3

### Declare variable a with initial value 2.0 and get it's data type by using type function, repeat by another variables with another data types

In [10]:
x=2.0
print(type(x))
y=2
print(type(y))

<class 'float'>
<class 'int'>

### Declare string variable with value "I am in we school, grade 1"  ,then:

In [11]:
x="iamin"
y="weschool"
z=",gradel"
print (x+y+z)

iaminweschool,gradel

#### 1) get length of it

In [1]:
len (x+y+z)

20

#### 2) check if word "WE" is in the string or not

In [2]:
type("WE")

str

#### 3)Modify string to "I am in we school,grade 2" by using replace() method

In [15]:
print (text.replace("1","2"))

iaminweschool,grade2

#### 4)Modify string to be in uppercase (capital letters)

In [16]:
print (text.upper)

<built-in method upper of str object at 0x7f3df6e49030>

#### 5) Split string on every white space (  )

In [16]:
print ("text".split)

<built-in method split of str object at 0x7f3a2ec62930>

#### 6) Write the sring by format method with words "I" and "we" and "school" as variables

In [2]:
x= "iam"
y= "inwe"
z= "school"
print (x+y+z)

iaminweschool

### Divide 11 by 2 and get result in float form

In [3]:
x=11/2
print (x)

5.5

### Divide 11 by 2 and get result in integer form

In [4]:
x=11//2
print (x)

5

### Divide 11 by 2 and get result in string form by using casting

In [6]:
x=11//2
z=str(x)
print (z)

5

### Get the reminder when you divide 11 by 2

In [7]:
11%2

1

### Make user enter his age as input, then add 5 to his age. (make the required to prevent error ocuured)

In [ ]:
x= input("age+5")

### Declare variable with boolean value, then print it's type by using type function

In [3]:
X="False"
print (type(X))

<class 'str'>

### Declare this list in variable ['tennis','swimmig','pingpong','handball','volley']

In [4]:
x=["tennis" , "swimming" , "pingpong" , "handball" , "volley"]
print (x)

['tennis', 'swimming', 'pingpong', 'handball', 'volley']

### 1) access item "pingpong" from the list

In [5]:
print (x[2])

pingpong

### 2) access items from swimming to handball in list by using range index

In [6]:
print (x[1:4])

['swimming', 'pingpong', 'handball']

### 3) Modify list to be ['tennis','swimming','pingpong','football','volley'] without declaring new list

x.remove("handball)
x.insert(3,"football")
print (x)

### 4) add item 'squash' at order number 3 in list

In [9]:
print (x)
x[3]="squash"
print (x)

['tennis', 'swimming', 'pingpong', 'handball', 'volley']
['tennis', 'swimming', 'pingpong', 'squash', 'volley']

### 5) add item 'karatee' at the end of the list

In [10]:
x.append("karatee")
print (x)

['tennis', 'swimming', 'pingpong', 'squash', 'volley', 'karatee']

### 6) remove 'tennis' from list

In [11]:
x.remove("tennis")
print (x)

NameError: name 'x' is not defined

### 7) Sort this list in both ascending and descending orders

### 8)Declare new list ['running','walking'] then merge it with the main previous list